package com.student.utils;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * TextCleaner 单元测试
 */
class TextCleanerTest {

    private final TextCleaner cleaner = new TextCleaner();

    // ===================== removeCitationMarkers =====================

    @Test
    void testRemoveCitationMarkers_SingleNumber() {
        String result = cleaner.removeCitationMarkers("参考[1]文献");
        assertEquals("参考文献", result);
    }

    @Test
    void testRemoveCitationMarkers_Range() {
        String result = cleaner.removeCitationMarkers("见[2-5]节内容");
        assertEquals("见节内容", result);
    }

    @Test
    void testRemoveCitationMarkers_MultipleRefs() {
        String result = cleaner.removeCitationMarkers("参见[1,3,5]文献");
        assertEquals("参见文献", result);
    }

    @Test
    void testRemoveCitationMarkers_WithSpaces() {
        String result = cleaner.removeCitationMarkers("参考[1, 2, 5]文献");
        assertEquals("参考文献", result);
    }

    @Test
    void testRemoveCitationMarkers_NonNumericNotRemoved() {
        String result = cleaner.removeCitationMarkers("诊断[治疗]方案");
        assertEquals("诊断[治疗]方案", result, "含文字的方括号不应被移除");
    }

    @Test
    void testRemoveCitationMarkers_Null_ReturnsNull() {
        assertNull(cleaner.removeCitationMarkers(null));
    }

    @Test
    void testRemoveCitationMarkers_Blank_ReturnsBlank() {
        assertEquals("", cleaner.removeCitationMarkers("   "));
    }

    // ===================== normalizeWhitespace =====================

    @Test
    void testNormalizeWhitespace_MultipleSpaces() {
        String result = cleaner.normalizeWhitespace("a   b    c");
        assertEquals("a b c", result);
    }

    @Test
    void testNormalizeWhitespace_TabsToSpace() {
        String result = cleaner.normalizeWhitespace("a\t\tb\tc");
        assertEquals("a b c", result);
    }

    @Test
    void testNormalizeWhitespace_ExcessNewlines() {
        String result = cleaner.normalizeWhitespace("段落1\n\n\n\n段落2");
        assertEquals("段落1\n\n段落2", result);
    }

    @Test
    void testNormalizeWhitespace_TrailingWhitespace() {
        String result = cleaner.normalizeWhitespace("  文本内容  \n\n  ");
        assertEquals("文本内容", result);
    }

    // ===================== fixBrokenLines =====================

    @Test
    void testFixBrokenLines_ChineseChar() {
        String result = cleaner.fixBrokenLines("中\n文");
        assertEquals("中文", result);
    }

    @Test
    void testFixBrokenLines_ChineseCharWithSpaces() {
        String result = cleaner.fixBrokenLines("诊 \n 断");
        assertEquals("诊断", result);
    }

    @Test
    void testFixBrokenLines_MultiCharNoFix() {
        String result = cleaner.fixBrokenLines("中文\n英文");
        assertEquals("中文\n英文", result, "多字符中文不应被修复");
    }

    @Test
    void testFixBrokenLines_MixedCjkAndNonCjk() {
        String result = cleaner.fixBrokenLines("word\n中\n文\n继续");
        assertEquals("word\n中文\n继续", result);
    }

    // ===================== removeHeadersFooters =====================

    @Test
    void testRemoveHeadersFooters_RepeatedLinesRemoved() {
        String text = "第1章 概述\n正文内容第一段\n第1章 概述\n正文内容第二段\n第1章 概述\n正文内容第三段\n第1章 概述\n正文内容第四段";
        String result = cleaner.removeHeadersFooters(text);
        assertFalse(result.contains("第1章 概述"));
        assertTrue(result.contains("正文内容"));
    }

    @Test
    void testRemoveHeadersFooters_UniqueLinesPreserved() {
        String text = "标题一\n内容A\n标题二\n内容B\n标题三\n内容C";
        String result = cleaner.removeHeadersFooters(text);
        assertTrue(result.contains("标题一"));
        assertTrue(result.contains("标题二"));
        assertTrue(result.contains("标题三"));
    }

    @Test
    void testRemoveHeadersFooters_LongLineNotRemoved() {
        // 行长度超过 100 字符的不应被判定为页眉页脚
        String longLine = "A".repeat(101);
        String text = longLine + "\n正文\n" + longLine + "\n正文\n" + longLine + "\n正文";
        String result = cleaner.removeHeadersFooters(text);
        assertTrue(result.contains(longLine), "长行不应被当作页眉页脚移除");
    }

    // ===================== removeMetadata =====================

    @Test
    void testRemoveMetadata_AnnasArchive_ShouldRemove() {
        String text = "Document generated by Anna's Archive around 2023-2024 as part of the DuXiu collection.\n\n正文内容开始";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("Anna's Archive"));
        assertFalse(result.contains("DuXiu"));
        assertTrue(result.contains("正文内容开始"));
    }

    @Test
    void testRemoveMetadata_AnnasArchiveUrl_ShouldRemove() {
        String text = "Downloaded from annas-archive.org\n\n第一章 引言";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("annas-archive"));
        assertTrue(result.contains("第一章 引言"));
    }

    @Test
    void testRemoveMetadata_FilenameDecoded_ShouldRemove() {
        String text = "filename_decoded: medical_book_2023.pdf\npdg_dir_name: /archives/2023\n\n医学影像诊断在临床实践中不可或缺。";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("filename_decoded"));
        assertFalse(result.contains("pdg_dir_name"));
        assertTrue(result.contains("医学影像诊断"));
    }

    @Test
    void testRemoveMetadata_JsonMetadata_ShouldRemove() {
        String jsonMeta = "{\"header_md5\": \"d449813237fce9f51ded4a41db142506\", "
                + "\"sha1\": \"f9cb16a85d22bac1afe1bc3a52a9c68fb3d90fdc\", "
                + "\"sha256\": \"9cc6f49f0f441714aaf7b818a590b9248\"}";
        String text = jsonMeta + "\n\n临床诊断结果如下所示。";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("header_md5"));
        assertFalse(result.contains("sha1"));
        assertTrue(result.contains("临床诊断结果"));
    }

    @Test
    void testRemoveMetadata_Crc32Json_ShouldRemove() {
        String text = "\"crc32\": 432761,\n\"filename_decoded\": \"book_001.pdf\"\n\n药物治疗方案包括抗生素。";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("crc32"));
        assertFalse(result.contains("filename_decoded"));
        assertTrue(result.contains("药物治疗方案"));
    }

    @Test
    void testRemoveMetadata_NormalMedicalText_ShouldNotRemove() {
        String text = "根据临床诊断结果显示，患者患有高血压和糖尿病。\n\n治疗方案包括药物治疗和生活方式干预。";
        String result = cleaner.removeMetadata(text);
        assertEquals(text, result);
    }

    @Test
    void testRemoveMetadata_NormalJsonArray_WithoutMetadataKeys_ShouldPreserve() {
        // JSON 结构但无元数据专属 key → 不剔除（可能是正文中的表格数据）
        String text = "[{\"name\": \"张三\", \"age\": 45, \"diagnosis\": \"高血压\"}]";
        String result = cleaner.removeMetadata(text);
        assertEquals(text, result);
    }

    @Test
    void testRemoveMetadata_MixedContent_ShouldOnlyRemoveMetadata() {
        String text = "Downloaded from annas-archive.org\n"
                + "\n\n第一章 引言\n"
                + "医学影像诊断在临床实践中不可或缺。\n"
                + "\n\n{\"header_md5\": \"abc123\", \"sha1\": \"def456\"}\n"
                + "\n\n第二章 方法与材料";
        String result = cleaner.removeMetadata(text);
        assertFalse(result.contains("annas-archive"));
        assertFalse(result.contains("header_md5"));
        assertTrue(result.contains("第一章 引言"));
        assertTrue(result.contains("医学影像诊断"));
        assertTrue(result.contains("第二章 方法与材料"));
    }

    @Test
    void testRemoveMetadata_Null_ReturnsNull() {
        assertNull(cleaner.removeMetadata(null));
    }

    @Test
    void testRemoveMetadata_Blank_ReturnsBlank() {
        assertEquals("", cleaner.removeMetadata("   \n  \t  "));
    }

    // ===================== clean 集成测试 =====================

    @Test
    void testClean_Integration_AllRulesApplied() {
        String input = "Document generated by Anna's Archive\n\n第1章 概述\n参考[1]文献显示该药物对治疗高血压有效[2,3]。\n中\n文断行需要修  复。\n\n\n\n\n多余空行。\n第1章 概述\n更多内容。\n第1章 概述";
        String result = cleaner.clean(input);
        // 元数据已去除
        assertFalse(result.contains("Anna's Archive"));
        // 页眉页脚已去除
        assertFalse(result.contains("第1章 概述"));
        // 引用已去除
        assertFalse(result.contains("[1]"));
        assertFalse(result.contains("[2,3]"));
        // 断行已修复（中\n文 → 中文）
        assertTrue(result.contains("中文断行"));
        // 多空格已规范化为单空格
        assertFalse(result.contains("修  复"));
        // 多余空行已规范化
        assertFalse(result.contains("\n\n\n\n"));
    }

    @Test
    void testClean_Null_ReturnsNull() {
        assertNull(cleaner.clean(null));
    }

    @Test
    void testClean_Blank_ReturnsBlank() {
        assertEquals("", cleaner.clean("   \n  \t  "));
    }
}
